---
- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: push image to registry
      docker_image:
        name: auth
        repository: http://registry:5000
        tag: "{{ lookup('env', 'BUILD_ID') }}"
        push: yes
        source: local

    - name: deploy to docker swarm
      docker_swarm_service:
        name: auth
        image: "registry/auth:{{ lookup('env', 'BUILD_ID') }}"
        networks:
          - name: "net_dev"
        env:
          AUTH_DB_URI: "jdbc:postgresql://postgres_dev:5432/dev"
          AUTH_DB_USER: "dev"
#         some env variables are skipped because they are not needed for test/qa, should be set for production
        secrets:
          - secret_name: postgres_dev_password
            filename: "/run/secrets/postgres_password"

